### PR TITLE
chore(decider): Refactor aqua code

### PR DESCRIPTION
**Pull request by InversionSpaces**
Mostly use new aqua boolean algebra

### CODE REVIEW

**Review by kmd-fl — COMMENTED** [review]
It looks nice but I feel there are more places where you can use the new feature. Did you want just to set an example or really want to remove the old approach?

**Comment by InversionSpaces** [comment]
I am trying to bring new aqua features to all the places I could reach, so tell me if I missed some.
Yes, I am trying to set an example, and yes, I am trying to remove ugly boolean functions so that eventually we could remove them in `builtin`

**Comment by kmd-fl** [comment]
@InversionSpaces I just do `git grep '== false'` and find a lot of examples, for one, in hex.aqua

**Comment by InversionSpaces** [comment]
Blocked by LNG-260

**Review by kmd-fl — APPROVED** [review]

**Pull request merged**
